In [1]:
import torch

In [2]:
x = torch.tensor(2.0, requires_grad=True)

In [3]:
y = 2*x**4 + x**3 + 3*x**2 + 5*x + 1

In [4]:
y

tensor(63., grad_fn=<AddBackward0>)

In [8]:
y.backward()

In [9]:
x.grad

tensor(93.)

In [10]:
# y' = 8x^3 + 3x^2 + 6x + 5

In [12]:
x = torch.tensor([[1, 2, 3], [3, 2, 1]], dtype=torch.float32, requires_grad=True)

In [13]:
print(x)

tensor([[1., 2., 3.],
        [3., 2., 1.]], requires_grad=True)


In [14]:
y = 3*x + 2

In [15]:
y

tensor([[ 5.,  8., 11.],
        [11.,  8.,  5.]], grad_fn=<AddBackward0>)

In [16]:
z = 2*y**2

In [17]:
z

tensor([[ 50., 128., 242.],
        [242., 128.,  50.]], grad_fn=<MulBackward0>)

In [18]:
out = z.mean()

In [19]:
print(out)

tensor(140., grad_fn=<MeanBackward0>)


In [20]:
out.backward()

In [21]:
print(x.grad)

tensor([[10., 16., 22.],
        [22., 16., 10.]])
